
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class CreateOrUpdateBalancingPoolParameters {
    /**
    * Label: Update Action, type: select
    */
    String updateAction
    /**
    * Label: Partition Name, type: entry
    */
    String partitionName
    /**
    * Label: Pool Name, type: entry
    */
    String poolName
    /**
    * Label: Optional Parameters, type: textarea
    */
    String optionalParameters
    /**
    * Label: Result Property Sheet, type: entry
    */
    String resultPropertySheet

    static CreateOrUpdateBalancingPoolParameters initParameters(StepParameters sp) {
        CreateOrUpdateBalancingPoolParameters parameters = new CreateOrUpdateBalancingPoolParameters()

        def updateAction = sp.getRequiredParameter('updateAction').value
        parameters.updateAction = updateAction
        def partitionName = sp.getRequiredParameter('partitionName').value
        parameters.partitionName = partitionName
        def poolName = sp.getRequiredParameter('poolName').value
        parameters.poolName = poolName
        def optionalParameters = sp.getParameter('optionalParameters').value
        parameters.optionalParameters = optionalParameters
        def resultPropertySheet = sp.getRequiredParameter('resultPropertySheet').value
        parameters.resultPropertySheet = resultPropertySheet

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: ea65b9e370adee8716d1e0a801c11e8b ===
