
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class CreateOrUpdatePoolMemberParameters {
    /**
    * Label: Update Action, type: select
    */
    String updateAction
    /**
    * Label: Member, type: entry
    */
    String member
    /**
    * Label: Pool Name, type: entry
    */
    String poolName
    /**
    * Label: Optional Parameters, type: textarea
    */
    String optionalParameters
    /**
    * Label: Result Property Sheet, type: entry
    */
    String resultPropertySheet

    static CreateOrUpdatePoolMemberParameters initParameters(StepParameters sp) {
        CreateOrUpdatePoolMemberParameters parameters = new CreateOrUpdatePoolMemberParameters()

        def updateAction = sp.getRequiredParameter('updateAction').value
        parameters.updateAction = updateAction
        def member = sp.getRequiredParameter('member').value
        parameters.member = member
        def poolName = sp.getRequiredParameter('poolName').value
        parameters.poolName = poolName
        def optionalParameters = sp.getParameter('optionalParameters').value
        parameters.optionalParameters = optionalParameters
        def resultPropertySheet = sp.getRequiredParameter('resultPropertySheet').value
        parameters.resultPropertySheet = resultPropertySheet

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 5b73202abd17ecb42fd253699e873cf6 ===
