
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class DeleteBalancingPoolParameters {
    /**
    * Label: , type: entry
    */
    String partitionName
    /**
    * Label: Pool Name, type: entry
    */
    String poolName
    /**
    * Label: Result Property Sheet, type: entry
    */
    String resultPropertySheet

    static DeleteBalancingPoolParameters initParameters(StepParameters sp) {
        DeleteBalancingPoolParameters parameters = new DeleteBalancingPoolParameters()

        def partitionName = sp.getRequiredParameter('partitionName').value
        parameters.partitionName = partitionName
        def poolName = sp.getRequiredParameter('poolName').value
        parameters.poolName = poolName
        def resultPropertySheet = sp.getRequiredParameter('resultPropertySheet').value
        parameters.resultPropertySheet = resultPropertySheet

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: a6522d10bd92e8a1058580fecd5953bc ===
