
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class DeleteBalancingPoolMemberParameters {
    /**
    * Label: , type: entry
    */
    String partitionName
    /**
    * Label: Pool Name, type: entry
    */
    String poolName
    /**
    * Label: Member Name, type: entry
    */
    String memberName
    /**
    * Label: Result Property Sheet, type: entry
    */
    String resultPropertySheet

    static DeleteBalancingPoolMemberParameters initParameters(StepParameters sp) {
        DeleteBalancingPoolMemberParameters parameters = new DeleteBalancingPoolMemberParameters()

        def partitionName = sp.getRequiredParameter('partitionName').value
        parameters.partitionName = partitionName
        def poolName = sp.getRequiredParameter('poolName').value
        parameters.poolName = poolName
        def memberName = sp.getRequiredParameter('memberName').value
        parameters.memberName = memberName
        def resultPropertySheet = sp.getRequiredParameter('resultPropertySheet').value
        parameters.resultPropertySheet = resultPropertySheet

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: f2ffaf11470c8c73173e911b208e96e0 ===
