
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class DisableNodeParameters {
    /**
    * Label: , type: entry
    */
    String partitionName
    /**
    * Label: , type: entry
    */
    String nodeName

    static DisableNodeParameters initParameters(StepParameters sp) {
        DisableNodeParameters parameters = new DisableNodeParameters()

        def partitionName = sp.getRequiredParameter('partitionName').value
        parameters.partitionName = partitionName
        def nodeName = sp.getRequiredParameter('nodeName').value
        parameters.nodeName = nodeName

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 961d89c5771c936d28c8a50e6e5f8c88 ===
