
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class EnableNodeParameters {
    /**
    * Label: , type: entry
    */
    String partitionName
    /**
    * Label: , type: entry
    */
    String nodeName

    static EnableNodeParameters initParameters(StepParameters sp) {
        EnableNodeParameters parameters = new EnableNodeParameters()

        def partitionName = sp.getRequiredParameter('partitionName').value
        parameters.partitionName = partitionName
        def nodeName = sp.getRequiredParameter('nodeName').value
        parameters.nodeName = nodeName

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: cef6c50364eb4285e4a6f4790f6d2e4e ===
