
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class GetBalancingPoolParameters {
    /**
    * Label: , type: entry
    */
    String partitionName
    /**
    * Label: Pool Name, type: entry
    */
    String poolName
    /**
    * Label: Result Property Sheet, type: entry
    */
    String resultPropertySheet

    static GetBalancingPoolParameters initParameters(StepParameters sp) {
        GetBalancingPoolParameters parameters = new GetBalancingPoolParameters()

        def partitionName = sp.getRequiredParameter('partitionName').value
        parameters.partitionName = partitionName
        def poolName = sp.getRequiredParameter('poolName').value
        parameters.poolName = poolName
        def resultPropertySheet = sp.getRequiredParameter('resultPropertySheet').value
        parameters.resultPropertySheet = resultPropertySheet

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 2813cfd121e8bb6381c1d7dbf7c89cd9 ===
