
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class GetBalancingPoolListParameters {
    /**
    * Label: , type: entry
    */
    String partitionName
    /**
    * Label: Result Property Sheet, type: entry
    */
    String resultPropertySheet

    static GetBalancingPoolListParameters initParameters(StepParameters sp) {
        GetBalancingPoolListParameters parameters = new GetBalancingPoolListParameters()

        def partitionName = sp.getRequiredParameter('partitionName').value
        parameters.partitionName = partitionName
        def resultPropertySheet = sp.getRequiredParameter('resultPropertySheet').value
        parameters.resultPropertySheet = resultPropertySheet

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 91d264165c4625c23400488ccf767eb6 ===
