
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class GetBalancingPoolMemberListParameters {
    /**
    * Label: , type: entry
    */
    String partitionName
    /**
    * Label: Pool Name, type: entry
    */
    String poolName
    /**
    * Label: Result Property Sheet, type: entry
    */
    String resultPropertySheet

    static GetBalancingPoolMemberListParameters initParameters(StepParameters sp) {
        GetBalancingPoolMemberListParameters parameters = new GetBalancingPoolMemberListParameters()

        def partitionName = sp.getRequiredParameter('partitionName').value
        parameters.partitionName = partitionName
        def poolName = sp.getRequiredParameter('poolName').value
        parameters.poolName = poolName
        def resultPropertySheet = sp.getRequiredParameter('resultPropertySheet').value
        parameters.resultPropertySheet = resultPropertySheet

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 01585c05952fb9c502c7799dd7355277 ===
