
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class ListPoolsParameters {
    /**
    * Label: , type: entry
    */
    String partitionName

    static ListPoolsParameters initParameters(StepParameters sp) {
        ListPoolsParameters parameters = new ListPoolsParameters()

        def partitionName = sp.getRequiredParameter('partitionName').value
        parameters.partitionName = partitionName

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: beadeccaebbd1a91f548fa14b515622d ===
